### ISSUE TITLE
stardew-site

### ISSUE THREAD

**Issue by jele77** [sdutry/leissman#16]
add a Banner and a list with 5 pictures and 5 texts, the pictures are also links to another website

**Comment by sdutry** [comment]
Things i'll need for this:
* Banner
* pictures (or their urls)
* texts
* links
* preferred layout
  * accordeon?
  * slider?
  * panels?
  * ...?

**Comment by jele77** [comment]
![stardewfertig](https://user-images.githubusercontent.com/30840659/29965546-4536a44a-8f0e-11e7-81df-566704c85057.png)

**Comment by jele77** [comment]
On Sundays Stardew Valley streams will happen.

My farms
jele is my first file and maru my first love
![jeleyear6fall](https://user-images.githubusercontent.com/30840659/29965561-57aafa2c-8f0e-11e7-8a5a-37023d65082d.png) 

Jenny is the second file, she was quite fast and efficient. She also dated all the singles before she married sebastian ^^
![jennyyear4spring](https://user-images.githubusercontent.com/30840659/29965571-65cf79b6-8f0e-11e7-9881-92253eba199a.png)

Chillda was the chilled run. Right now she is overworking herself and building a Megafarm :-D 1.5k crops are too much to handle
![chilldayear3spring](https://user-images.githubusercontent.com/30840659/29965584-71823e56-8f0e-11e7-893c-f5b73516c1ac.png)

Elise is a Hearthstone character and i want her Farm to be Ungoro themed, that means i mainly farm Ancient fruit and Dinos. She also could finish the CC in year one (and she is a man by mistake)
![eliseyear2spring](https://user-images.githubusercontent.com/30840659/29965593-797263a2-8f0e-11e7-9f81-c995d272e7df.png)

Johnny T. is the evil and funky Joja run. I am really looking forward to be mean to the whole city.
![johnnytyear1spring](https://user-images.githubusercontent.com/30840659/29965608-872542d0-8f0e-11e7-88ed-4dc5e03c87ed.png)

**Comment by jele77** [comment]
Here is the pictures and the text, that got to be on the stardew site <3. i dont have an idea for the layout? thought it could be just a list to scroll down. if yuo have something more userfriendly, just do that

**Comment by jele77** [comment]
i think we dont need the links actually

**Comment by jele77** [comment]
![stardewfertig](https://user-images.githubusercontent.com/30840659/29967416-d454dca2-8f16-11e7-8c11-8e71b6401c74.png) without typo hopefully

**Comment by sdutry** [comment]
Page should be ready according with your input.

Please let me know if there's anything that needs to change.
[https://leissman.herokuapp.com/stardew.html](https://leissman.herokuapp.com/stardew.html)

**Comment by jele77** [comment]
seems good
