### ISSUE TITLE
Add a link to twitch on jele island image

### ISSUE THREAD

**Issue by sdutry** [sdutry/leissman#5]

**Comment by sdutry** [comment]
link should be on the twitch logo

**Comment by jele77** [comment]
Right now i think its not userfriendly to leave the website right to twitch. I think we need a twitch page, where i have a short text, what my visions as a streamer are, you have a picture of me and then the link. (Its confusing for users to getlinked to a diffrent site right away. Sorry i needed some time to understand that). We leave it like this, till i have those pictures ready
